# POST http://localhost:3001/api/persons 
#https://morning-taiga-32865.herokuapp.com/api/persons
POST http://localhost:3001/api/persons 
content-type: application/json

{
  "name": "Teppo Testinen",
  "number": "53242342"
}